qa/tasks/deepsea: fix indexing of iterator
Address errors like:
  TypeError: 'dict_keys' object does not support indexing

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>